# Generated by Django 3.2.9 on 2022-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumb',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
