# Generated by Django 3.2.9 on 2022-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='thumb',
        ),
        migrations.AddField(
            model_name='song',
            name='audioFile',
            field=models.FileField(default='null', upload_to='songs/'),
        ),
    ]
